// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKlO19YqBNFPfVpCXVu2C7lmWOQ5zbnls',
    appId: '1:253826418328:web:366e15716e418d4d1e72ed',
    messagingSenderId: '253826418328',
    projectId: 'postmanapp-94bb8',
    authDomain: 'postmanapp-94bb8.firebaseapp.com',
    storageBucket: 'postmanapp-94bb8.firebasestorage.app',
    measurementId: 'G-3E92GXH59X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvaRTbxYKNsY_EtE6yqxY2FtTYYMLcqeA',
    appId: '1:253826418328:android:408fe98c943a1e241e72ed',
    messagingSenderId: '253826418328',
    projectId: 'postmanapp-94bb8',
    storageBucket: 'postmanapp-94bb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClesFCKWe8mM9D4XuH0pR8W9HFIou80u0',
    appId: '1:253826418328:ios:d0002e224166b2381e72ed',
    messagingSenderId: '253826418328',
    projectId: 'postmanapp-94bb8',
    storageBucket: 'postmanapp-94bb8.firebasestorage.app',
    iosBundleId: 'com.example.postmanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClesFCKWe8mM9D4XuH0pR8W9HFIou80u0',
    appId: '1:253826418328:ios:d0002e224166b2381e72ed',
    messagingSenderId: '253826418328',
    projectId: 'postmanapp-94bb8',
    storageBucket: 'postmanapp-94bb8.firebasestorage.app',
    iosBundleId: 'com.example.postmanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKlO19YqBNFPfVpCXVu2C7lmWOQ5zbnls',
    appId: '1:253826418328:web:f155198a497d15981e72ed',
    messagingSenderId: '253826418328',
    projectId: 'postmanapp-94bb8',
    authDomain: 'postmanapp-94bb8.firebaseapp.com',
    storageBucket: 'postmanapp-94bb8.firebasestorage.app',
    measurementId: 'G-L2SHGQ0TZV',
  );

}